services:
  fulfilment:
    hostname: mvc
    build:
      context: .
    ports:
      - "8080:8080"
    expose:
      - 8080
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 270M
