name: VTCC Pull Request

on:
  create:
    branches:
      - '**'
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'adopt'

        - name: Build and Test
          run:  make b

        - name: Build and Test Fail!
          if: failure()
          run: |
            make print-error-report
