name: asnsei-the-right-waf Pull Request

on:
  pull_request_target:
    branches:
      - '**'
  create:
    branches:
      - '**'
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'adopt'

        - name: Build and Test
          run:  make b
