name: VTCC Build

on:
  pull_request:
    types:
      - closed
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 24
          uses: actions/setup-java@v4
          with:
            java-version: '24'
            distribution: 'adopt'

        - name: Build and Test
          run:  make b

        - name: Build and Test Fail!
          if: failure()
          run: |
            make print-error-report
